add_newline = false 

[hostname]
disabled = true
ssh_only = true

[shell]
disabled = false
zsh_indicator = "z"
bash_indicator = ">>"
style = "cyan bold"

[kubernetes]
disabled = false

[nats]
disabled = false
style = "bold red"
