#!/usr/bin/env bash

test ! -n "${1}" && echo "must provide sha" && exit 1

sha=${1:-}
model=${2:-gpt-4o}

git log "${sha}"..HEAD | mods -m "${model}" "Write a concise pull request for these changes. Use markdown formatting. You are an very senior developer."
