#!/usr/bin/env bash

set -e

test ! -n "${SCRIPTS}" && echo "SCRIPTS not set" && exit 1
test ! -n "${1}" && echo "usage: newscript <name>" && exit 1

path="${SCRIPTS}/${1}"

if [ -e "${path}" ]; then
	if
		command -v gum >/dev/null 2>&1
	then
		gum confirm "${1} already exists. Edit?"
		exec $EDITOR "${path}"
	else
		read -p "${1} already exists. Edit? " yes
		case "${yes}" in
		y | yes | yep | yeppers | yeah | ok | okay) exec $EDITOR "${path}" ;;
		esac
	fi
	exit 0
fi

printf "#!/usr/bin/env bash\n\n" >"${path}"
chmod +x "${path}"
exec $EDITOR +2 "${path}"
