#!/usr/bin/env python3

import argparse
import json
import requests
from os import path

def send_link(args):
    url = args.url
    title = args.title
    description = args.description

    if not url or not title:
        print("Both title and url must be provided")
        return

    key_file_path = path.expanduser('~/.config/me/transporter/key')
    with open(key_file_path, 'r') as file:
        key = file.readline().strip()

    payload = {
        "description": description,
        "title": title,
        "tag_names": ["sendlink"],
        "url": url,
    }

    headers = {
        'X-API-KEY': key,
        'Content-Type': 'application/json'
    }

    response = requests.post('https://transporter.infra.ptco.rocks/link',
headers=headers, data=json.dumps(payload))

    print(json.dumps(response.json(), indent=4))

def main():
    parser = argparse.ArgumentParser(description='Send a link.')
    parser.add_argument('url', help='The URL to send.')
    parser.add_argument('title', help='The title of the link.')
    parser.add_argument('-d', '--description', default="no description", help='The description of the link.')
    args = parser.parse_args()

    send_link(args)

if __name__ == "__main__":
    main()
