#!/bin/bash

set -euo

tools=(
  act
  jo
  nats-server
  fx
  gnupg
  pinentry-mac
  obs
  slack
  bat
  tlrc
  fd
  rg
  eza
  htop
  neovim
  fastfetch
  zoxide
  fzf
  zed
  visual-studio-code
  stripe-cli
  vlc
  kap
  podman
  podman-desktop
  fd
  gum
  sshs
  arkade
  alt-tab
  # firefox
  brave-browser
  font-jetbrains-mono-nerd-font
  hiddenbar
  itsycal
  kap
  rectangle
  wezterm
  tailscale
  yazi
  atlas
  git-lfs
)

langs=(
  go
  node
  pnpm
  uv
)

for i in "${tools[@]}"; do
  printf "Installing %s\n" "${i}"
  brew install "${i}"
done

for i in "${langs[@]}"; do
  printf "Installing %s\n" "${i}"
  brew install "${i}"
done
